/**
 * This file is auto-generated by grpc-helper
 */

/* eslint-disable @typescript-eslint/no-namespace */

import * as grpc from '@midwayjs/grpc';

/* package user start */
export namespace user {
  // 服务的定义
  export interface Greeter {
    // Sends a greeting
    login(data: LoginRequest): Promise<UserReply>;
    register(data: RegisterRequest): Promise<UserReply>;
    verify(data: VerifyRequest): Promise<UserReply>;
  }
  /**
   * Greeter client interface
   */
  export interface GreeterClient {
    // Sends a greeting
    login(
      options?: grpc.IClientOptions
    ): grpc.IClientUnaryService<LoginRequest, UserReply>;
    register(
      options?: grpc.IClientOptions
    ): grpc.IClientUnaryService<RegisterRequest, UserReply>;
    verify(
      options?: grpc.IClientOptions
    ): grpc.IClientUnaryService<VerifyRequest, UserReply>;
  }
  // 服务的请求参数
  export interface LoginRequest {
    username?: string;
    password?: string;
  }
  export interface RegisterRequest {
    username?: string;
    password?: string;
    checkPassword?: string;
    role?: string;
  }
  export interface VerifyRequest {
    code?: string;
  }
  // 服务的响应参数
  export interface Data {
    userId?: string;
    username?: string;
    role?: string;
    authorization?: string;
  }
  export interface UserReply {
    success?: boolean;
    message?: string;
    data?: user.Data;
  }
}
/* package user end */
